spring:
  # 配置数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springsecurity6_vue3
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置Mybatis Plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl